### ISSUE TITLE
请问能添加中文界面吗？

### ISSUE THREAD

**Issue by ansaset** [ShyKiss/Outlast-Picker#1]
首先在中文系统下 robocopy 命令用不了，所以我自行复制了相关的文件，并且成功运行，但是我想翻译成中文，所以我又打开了""OLGame\Localization\INT\Picker.int""里的文件，修改了中文，但是会乱码，于是我又切换到俄文，会变成方框并且不显示中文，如图所示，请问我该如何修改呢？

------Ниже приводится переведенный контент-------

Оригинальное название：
Могу ли я добавить китайский интерфейс?
Текст выглядит следующим образом:
Прежде всего, команда robocopy недоступна в китайской системе, поэтому я самостоятельно скопировал соответствующие файлы и успешно запустил ее, но я хотел перевести ее на китайский, поэтому открыл "" again.OLGame\Localization\INT\Picker.int " ", я изменил китайский, но он будет искажен, поэтому я снова переключился на русский, он превратится в коробку, а китайский не будет отображаться. Как показано на рисунке, как я могу его изменить?
[情况1](https://user-images.githubusercontent.com/75153154/148944244-5aa463da-2454-4e35-b248-c4a3acca32e9.png)
[情况2](https://user-images.githubusercontent.com/75153154/148943909-bfff4fd1-e381-43b9-8ca8-25076c6a520e.png)

**Comment by ShyKiss** [comment]
Chinese characters are not part of the font. You need to open Custom/Picker/Content/PickerDebugMenu.upk and change PickerFont by adding the offset of the characters. (That's where Calibri font stands.)

----------------------------------

汉字不是字体的一部分。你需要打开Custom/Picker/Content/PickerDebugMenu.upk，通过添加字符的偏移量来改变PickerFont。(这就是Calibri字体的位置）。

**Comment by ansaset** [comment]
谢谢您，但是我是个新手，对这些完全不懂，但我会尝试完成的，非常感谢
------
Thank you, but I'm a newbie and have absolutely no idea about these, but I'll try to get it done, thank you so much, and happy new year!

**Comment by ansaset** [comment]
谢谢您，但是我是个新手，对这些完全不懂，但我会尝试完成的，非常感谢，新年快乐！
-----
Thank you, but I'm a newbie and have absolutely no idea about these, but I'll try to get it done, thank you so much, and happy new year!

**Comment by ansaset** [comment]
好吧，我回来了，完全没有头绪，我对upk和虚幻引擎一点不了解，我试图用umodel_64.exe文件对PickerDebugMenu.upk解包，但是只有PickerFont_***.tga这样类似的文件，我用Adobe Photoshop打开看了一下，确实是一些字体文件，但我感觉我的方向错了，因为没办法打包。请问您能抽空帮忙做一下这个文件吗，万分感谢！
这是中文字体文件
Well, I'm back, totally clueless, I don't know anything about upk and unreal engine, I tried to unpack PickerDebugMenu.upk with umodel_64.exe file, but there are only similar files like PickerFont_***.tga, I use Adobe Photoshop opened it, and it was indeed some font files, but I felt that I was going in the wrong direction because there was no way to pack it. Could you please take the time to help with this document, thank you very much!
This is the Chinese font file
[Uploading 中文字体.zip…]()
如果您有空也可以发给我的邮箱--2011565866@qq.com--

**Comment by ShyKiss** [comment]
You need to open PickerDebugMenu.upk through UDK and load your font instead of PickerFont (With the same name). You can see a video on how to create a font in UDK :)

-----------------------------------------------

你需要通过UDK打开PickerDebugMenu.upk并加载你的字体，而不是PickerFont（同名）。你可以看看如何在UDK中创建字体的视频 :)

**Comment by ansaset** [comment]
sorry, this is the file
https://wwe.lanzouo.com/i4ZJpyp4lze

**Comment by ansaset** [comment]
sorry, i try now

**Comment by ShyKiss** [comment]
You need this UDK: https://drive.google.com/file/d/1IZed_3QAivpnU2uPlSClFVs-YOZrIpcd/view
